name: CI/CD Tienda Frontend

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Image to ECR
      env:
        REGISTRY: ${{ secrets.ECR_REGISTRY }}
        REPOSITORY: ${{ secrets.ECR_REPO_URL_FRONTEND }}
        IMAGE_TAG: v1
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f dockerfile .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # ==========================================
    # DESPLIEGUE EN EL FRONTEND (MAQUINA PUBLICA)
    # ==========================================
    - name: Deploy to Front EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          mkdir -p ~/app-frontend && cd ~/app-frontend
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_FRONTEND }}:v1
          docker stop tienda-frontend-despacho || true
          docker rm tienda-frontend-despacho || true
          docker run -d -p 80:80 --name tienda-frontend-despacho ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_FRONTEND }}:v1